#!/usr/bin/env python3
"""NaRA: Noise-Aware Low-Rank Adaptation for Diffusion LLMs.

Reference implementation of the adapter described in
    "NaRA: Noise-Aware LoRA for Parameter-Efficient Fine-Tuning of Diffusion LLMs"
    arXiv:2605.29716

Core idea (vs. plain LoRA h = W0 x + B A x):

    h = W0 x + B · C(λ) · A · x                     (per-layer adapted forward)
    C(λ) = I_r + η · F_φ(e_λ)                        (noise-aware core matrix)
    e_λ  = [cos(2π k λ) ⊕ sin(2π k λ)],  k ~ N(0, σ²)  (Gaussian Fourier embed)

where
    λ ∈ [0, 1]   is the noise level = fraction of masked tokens in the batch,
    A ∈ ℝ^{r×k}, B ∈ ℝ^{d×r}   are STATIC low-rank projections (as in LoRA),
    C(λ) ∈ ℝ^{r×r}   is a DYNAMIC core generated by a lightweight, GLOBALLY
                     SHARED hypernetwork F_φ conditioned on λ,
    η    is a small scaling factor (default 0.1) controlling how far C can move
         away from identity (and thus gradient flow to the hypernetwork).

Init: A ~ Kaiming, B = 0, hypernetwork final layer = 0 ⟹ C(λ) = I_r at step 0,
so NaRA's step-0 gradient is mathematically identical to standard LoRA and it
specializes from there.

Only {A, B, φ} are trained; the base model weights W0 stay frozen.
"""
from __future__ import annotations

import math
from typing import List, Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F


class GaussianFourierEmbedding(nn.Module):
    """Map scalar noise level λ ∈ [0,1] -> d-dim Fourier features.

    e_λ = [cos(2π k λ) ⊕ sin(2π k λ)],  k ~ N(0, σ²) (fixed, non-trainable).

    Mitigates the spectral bias of feeding a raw low-dim coordinate to an MLP,
    letting the hypernetwork respond to small changes in λ.
    """

    def __init__(self, dim: int, sigma: float = 1.0):
        super().__init__()
        assert dim % 2 == 0, "Fourier embedding dim must be even"
        # k is a fixed random projection; register as buffer so it is saved but
        # not trained and moves with .to(device).
        self.register_buffer("freqs", torch.randn(dim // 2) * sigma)

    def forward(self, lam: torch.Tensor) -> torch.Tensor:
        # lam: (...,) scalar per sample (or a 0-dim tensor). -> (..., dim)
        lam = lam.reshape(-1, 1)  # (N, 1)
        proj = 2.0 * math.pi * lam * self.freqs.view(1, -1)  # (N, dim/2)
        return torch.cat([proj.cos(), proj.sin()], dim=-1)  # (N, dim)


class NaRAHypernetwork(nn.Module):
    """Globally-shared network F_φ that produces the r×r core C(λ).

    C(λ) = I_r + η · reshape(MLP(e_λ), (r, r))

    Called ONCE per step; the resulting C is broadcast to every NaRA layer.
    """

    def __init__(
        self,
        rank: int,
        fourier_dim: int = 128,
        hidden_dim: int = 256,
        sigma: float = 1.0,
        eta: float = 0.1,
    ):
        super().__init__()
        self.rank = rank
        self.eta = eta
        self.embed = GaussianFourierEmbedding(fourier_dim, sigma=sigma)
        self.net = nn.Sequential(
            nn.Linear(fourier_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, rank * rank),
        )
        self._init_weights()

    def _init_weights(self):
        for m in self.net:
            if isinstance(m, nn.Linear):
                nn.init.kaiming_uniform_(m.weight, a=math.sqrt(5))
                if m.bias is not None:
                    nn.init.zeros_(m.bias)
        # Zero the FINAL layer so F_φ(·) = 0 at init  =>  C(λ) = I_r.
        last = self.net[-1]
        nn.init.zeros_(last.weight)
        nn.init.zeros_(last.bias)

    def forward(self, lam: torch.Tensor) -> torch.Tensor:
        """lam: scalar tensor or (batch,) -> C: (r, r) or (batch, r, r)."""
        squeeze = lam.dim() == 0 or (lam.dim() == 1 and lam.numel() == 1)
        e = self.embed(lam)  # (N, fourier_dim)
        delta = self.net(e).view(-1, self.rank, self.rank)  # (N, r, r)
        eye = torch.eye(self.rank, device=delta.device, dtype=delta.dtype)
        C = eye.unsqueeze(0) + self.eta * delta  # (N, r, r)
        return C[0] if squeeze else C


class NaRAController(nn.Module):
    """Owns the single shared hypernetwork and caches C(λ) for the current step.

    Usage per training step:
        controller.set_noise_level(lam)     # computes + caches C(λ) once
        logits = model(input_ids)           # every NaRALinear reads controller.C
    """

    def __init__(self, hypernetwork: NaRAHypernetwork):
        super().__init__()
        self.hypernetwork = hypernetwork
        self._C: Optional[torch.Tensor] = None

    def set_noise_level(self, lam: torch.Tensor) -> torch.Tensor:
        self._C = self.hypernetwork(lam)
        return self._C

    @property
    def C(self) -> torch.Tensor:
        if self._C is None:
            raise RuntimeError(
                "NaRA core matrix not set. Call controller.set_noise_level(lam) "
                "before the forward pass."
            )
        return self._C


class NaRALinear(nn.Module):
    """Wraps a frozen nn.Linear with a noise-aware low-rank update.

    h = base(x) + scaling · B · C(λ) · A · x
    """

    def __init__(
        self,
        base_linear: nn.Linear,
        controller: NaRAController,
        rank: int = 32,
        alpha: Optional[float] = None,
    ):
        super().__init__()
        self.base = base_linear
        for p in self.base.parameters():
            p.requires_grad_(False)  # W0 stays frozen

        self.controller = controller  # shared; not registered as a submodule param owner
        self.rank = rank
        in_f = base_linear.in_features
        out_f = base_linear.out_features
        alpha = rank if alpha is None else alpha
        self.scaling = alpha / rank

        # A: (r, in)  Kaiming ;  B: (out, r)  zeros  (=> ΔW = 0 at init)
        self.A = nn.Parameter(torch.empty(rank, in_f))
        self.B = nn.Parameter(torch.zeros(out_f, rank))
        nn.init.kaiming_uniform_(self.A, a=math.sqrt(5))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        base_out = self.base(x)
        C = self.controller.C  # (r, r) or (batch, r, r)

        a = F.linear(x, self.A)  # (..., r)   = A x
        # c = C(λ) · (A x) :  c[...,R] = Σ_r C[R,r] (Ax)[r]
        if C.dim() == 2:
            c = torch.einsum("...r,Rr->...R", a, C)
        else:
            # per-sample C; x is (batch, seq, in) -> a is (batch, seq, r)
            c = torch.einsum("bsr,bRr->bsR", a, C)
        update = F.linear(c, self.B)  # (..., out) = B c
        return base_out + self.scaling * update

    def merged_delta_weight(self) -> torch.Tensor:
        """Return ΔW = scaling · B C A for the currently-set λ (for inspection)."""
        C = self.controller.C
        if C.dim() != 2:
            raise ValueError("merged_delta_weight expects a scalar (r,r) C.")
        return self.scaling * (self.B @ C @ self.A)


# Default adapter targets: the attention Q/K/V/O projections (per the paper).
DEFAULT_TARGET_MODULES = ("q_proj", "k_proj", "v_proj", "o_proj")


def inject_nara(
    model: nn.Module,
    rank: int = 32,
    eta: float = 0.1,
    alpha: Optional[float] = None,
    fourier_dim: int = 128,
    hidden_dim: int = 256,
    sigma: float = 1.0,
    target_modules: Tuple[str, ...] = DEFAULT_TARGET_MODULES,
) -> Tuple[NaRAController, List[str]]:
    """Freeze `model`, replace target nn.Linear layers with NaRALinear, all
    sharing ONE globally-shared hypernetwork.

    Returns (controller, replaced_layer_names). Trainable params after this call:
    every NaRALinear's {A, B} plus the controller's hypernetwork φ.
    """
    for p in model.parameters():
        p.requires_grad_(False)

    hyper = NaRAHypernetwork(
        rank=rank, fourier_dim=fourier_dim, hidden_dim=hidden_dim, sigma=sigma, eta=eta
    )
    controller = NaRAController(hyper)

    replaced: List[str] = []
    for name, module in list(model.named_modules()):
        for child_name, child in list(module.named_children()):
            full = f"{name}.{child_name}" if name else child_name
            if isinstance(child, nn.Linear) and any(
                full.endswith(t) or child_name == t for t in target_modules
            ):
                setattr(
                    module,
                    child_name,
                    NaRALinear(child, controller, rank=rank, alpha=alpha),
                )
                replaced.append(full)
    if not replaced:
        raise ValueError(
            f"No layers matched target_modules={target_modules}. "
            "Inspect model.named_modules() and pass the right suffixes."
        )
    return controller, replaced


def nara_trainable_parameters(model: nn.Module, controller: NaRAController):
    """Yield exactly the NaRA parameters: per-layer {A, B} + hypernetwork φ."""
    for m in model.modules():
        if isinstance(m, NaRALinear):
            yield m.A
            yield m.B
    yield from controller.hypernetwork.parameters()


def nara_state_dict(model: nn.Module, controller: NaRAController) -> dict:
    """Compact adapter checkpoint (no base weights)."""
    sd = {"hypernetwork": controller.hypernetwork.state_dict(), "layers": {}}
    for name, m in model.named_modules():
        if isinstance(m, NaRALinear):
            sd["layers"][name] = {"A": m.A.detach().cpu(), "B": m.B.detach().cpu()}
    return sd
